// lib/fuseauxEtCategories.ts
import { type Langue } from './i18n'

// ── En-têtes de région ───────────────────────────────────────────────────────
export const REGIONS: Record<string, Record<Langue, string>> = {
  ameriques: { fr: '— AMÉRIQUES —', en: '— AMERICAS —', es: '— AMÉRICAS —', pt: '— AMÉRICAS —', ht: '— AMERIK —' },
  europe:    { fr: '— EUROPE —',    en: '— EUROPE —',   es: '— EUROPA —',   pt: '— EUROPA —',   ht: '— EWÒP —' },
  afrique:   { fr: '— AFRIQUE —',   en: '— AFRICA —',   es: '— ÁFRICA —',   pt: '— ÁFRICA —',   ht: '— AFRIK —' },
  asie:      { fr: '— ASIE —',      en: '— ASIA —',     es: '— ASIA —',     pt: '— ÁSIA —',     ht: '— AZI —' },
  oceanie:   { fr: '— OCÉANIE —',   en: '— OCEANIA —',  es: '— OCEANÍA —',  pt: '— OCEANIA —',  ht: '— OSEANI —' },
}

// ── Fuseaux horaires par région ──────────────────────────────────────────────
export const FUSEAUX_PAR_REGION: Record<string, { value: string; label: Record<Langue, string> }[]> = {
  ameriques: [
    { value: 'America/Port-au-Prince',         label: { fr: '🇭🇹 Haïti', en: '🇭🇹 Haiti', es: '🇭🇹 Haití', pt: '🇭🇹 Haiti', ht: '🇭🇹 Ayiti' } },
    { value: 'America/Guadeloupe',             label: { fr: '🇬🇵 Guadeloupe / Martinique', en: '🇬🇵 Guadeloupe / Martinique', es: '🇬🇵 Guadalupe / Martinica', pt: '🇬🇵 Guadalupe / Martinica', ht: '🇬🇵 Gwadloup / Matinik' } },
    { value: 'America/Santo_Domingo',          label: { fr: '🇩🇴 République Dominicaine', en: '🇩🇴 Dominican Republic', es: '🇩🇴 República Dominicana', pt: '🇩🇴 República Dominicana', ht: '🇩🇴 Repiblik Dominikèn' } },
    { value: 'America/Jamaica',                label: { fr: '🇯🇲 Jamaïque', en: '🇯🇲 Jamaica', es: '🇯🇲 Jamaica', pt: '🇯🇲 Jamaica', ht: '🇯🇲 Jamayik' } },
    { value: 'America/Havana',                 label: { fr: '🇨🇺 Cuba', en: '🇨🇺 Cuba', es: '🇨🇺 Cuba', pt: '🇨🇺 Cuba', ht: '🇨🇺 Kiba' } },
    { value: 'America/Puerto_Rico',            label: { fr: '🇵🇷 Porto Rico', en: '🇵🇷 Puerto Rico', es: '🇵🇷 Puerto Rico', pt: '🇵🇷 Porto Rico', ht: '🇵🇷 Pòtoriko' } },
    { value: 'America/New_York',               label: { fr: '🇺🇸 New York / Miami / Boston', en: '🇺🇸 New York / Miami / Boston', es: '🇺🇸 Nueva York / Miami / Boston', pt: '🇺🇸 Nova York / Miami / Boston', ht: '🇺🇸 New York / Miami / Boston' } },
    { value: 'America/Chicago',                label: { fr: '🇺🇸 Chicago / Houston', en: '🇺🇸 Chicago / Houston', es: '🇺🇸 Chicago / Houston', pt: '🇺🇸 Chicago / Houston', ht: '🇺🇸 Chicago / Houston' } },
    { value: 'America/Denver',                 label: { fr: '🇺🇸 Denver / Phoenix', en: '🇺🇸 Denver / Phoenix', es: '🇺🇸 Denver / Phoenix', pt: '🇺🇸 Denver / Phoenix', ht: '🇺🇸 Denver / Phoenix' } },
    { value: 'America/Los_Angeles',            label: { fr: '🇺🇸 Los Angeles / San Francisco', en: '🇺🇸 Los Angeles / San Francisco', es: '🇺🇸 Los Ángeles / San Francisco', pt: '🇺🇸 Los Angeles / São Francisco', ht: '🇺🇸 Los Angeles / San Francisco' } },
    { value: 'America/Montreal',               label: { fr: '🇨🇦 Montréal / Québec', en: '🇨🇦 Montreal / Quebec City', es: '🇨🇦 Montreal / Quebec', pt: '🇨🇦 Montreal / Quebec', ht: '🇨🇦 Monreyal / Kebèk' } },
    { value: 'America/Toronto',                label: { fr: '🇨🇦 Toronto / Ottawa', en: '🇨🇦 Toronto / Ottawa', es: '🇨🇦 Toronto / Ottawa', pt: '🇨🇦 Toronto / Ottawa', ht: '🇨🇦 Toronto / Otawa' } },
    { value: 'America/Vancouver',              label: { fr: '🇨🇦 Vancouver', en: '🇨🇦 Vancouver', es: '🇨🇦 Vancouver', pt: '🇨🇦 Vancouver', ht: '🇨🇦 Vankouve' } },
    { value: 'America/Mexico_City',            label: { fr: '🇲🇽 Mexique', en: '🇲🇽 Mexico', es: '🇲🇽 México', pt: '🇲🇽 México', ht: '🇲🇽 Meksik' } },
    { value: 'America/Bogota',                 label: { fr: '🇨🇴 Colombie', en: '🇨🇴 Colombia', es: '🇨🇴 Colombia', pt: '🇨🇴 Colômbia', ht: '🇨🇴 Kolonbi' } },
    { value: 'America/Lima',                   label: { fr: '🇵🇪 Pérou', en: '🇵🇪 Peru', es: '🇵🇪 Perú', pt: '🇵🇪 Peru', ht: '🇵🇪 Perou' } },
    { value: 'America/Santiago',               label: { fr: '🇨🇱 Chili', en: '🇨🇱 Chile', es: '🇨🇱 Chile', pt: '🇨🇱 Chile', ht: '🇨🇱 Chili' } },
    { value: 'America/Argentina/Buenos_Aires', label: { fr: '🇦🇷 Argentine', en: '🇦🇷 Argentina', es: '🇦🇷 Argentina', pt: '🇦🇷 Argentina', ht: '🇦🇷 Ajantin' } },
    { value: 'America/Sao_Paulo',              label: { fr: '🇧🇷 Brésil (São Paulo)', en: '🇧🇷 Brazil (São Paulo)', es: '🇧🇷 Brasil (São Paulo)', pt: '🇧🇷 Brasil (São Paulo)', ht: '🇧🇷 Brezil (Sao Paulo)' } },
    { value: 'America/Anchorage',              label: { fr: '🇺🇸 Alaska', en: '🇺🇸 Alaska', es: '🇺🇸 Alaska', pt: '🇺🇸 Alasca', ht: '🇺🇸 Alaska' } },
    { value: 'America/Halifax',                label: { fr: '🇨🇦 Halifax / Maritimes', en: '🇨🇦 Halifax / Maritimes', es: '🇨🇦 Halifax / Marítimas', pt: '🇨🇦 Halifax / Marítimas', ht: '🇨🇦 Halifax / Maritim' } },
    { value: 'America/Nassau',                 label: { fr: '🇧🇸 Bahamas', en: '🇧🇸 Bahamas', es: '🇧🇸 Bahamas', pt: '🇧🇸 Bahamas', ht: '🇧🇸 Bahamas' } },
    { value: 'America/Port_of_Spain',          label: { fr: '🇹🇹 Trinité-et-Tobago / Barbade', en: '🇹🇹 Trinidad and Tobago / Barbados', es: '🇹🇹 Trinidad y Tobago / Barbados', pt: '🇹🇹 Trinidad e Tobago / Barbados', ht: '🇹🇹 Trinidad-e-Tobago / Babad' } },
    { value: 'America/Caracas',                label: { fr: '🇻🇪 Venezuela', en: '🇻🇪 Venezuela', es: '🇻🇪 Venezuela', pt: '🇻🇪 Venezuela', ht: '🇻🇪 Venezyela' } },
    { value: 'America/Guyana',                 label: { fr: '🇬🇾 Guyana', en: '🇬🇾 Guyana', es: '🇬🇾 Guyana', pt: '🇬🇾 Guiana', ht: '🇬🇾 Giyàn' } },
    { value: 'America/Paramaribo',             label: { fr: '🇸🇷 Suriname', en: '🇸🇷 Suriname', es: '🇸🇷 Surinam', pt: '🇸🇷 Suriname', ht: '🇸🇷 Sirinam' } },
    { value: 'America/Asuncion',               label: { fr: '🇵🇾 Paraguay', en: '🇵🇾 Paraguay', es: '🇵🇾 Paraguay', pt: '🇵🇾 Paraguai', ht: '🇵🇾 Paragwe' } },
    { value: 'America/Montevideo',             label: { fr: '🇺🇾 Uruguay', en: '🇺🇾 Uruguay', es: '🇺🇾 Uruguay', pt: '🇺🇾 Uruguai', ht: '🇺🇾 Irigwe' } },
    { value: 'America/Guayaquil',              label: { fr: '🇪🇨 Équateur', en: '🇪🇨 Ecuador', es: '🇪🇨 Ecuador', pt: '🇪🇨 Equador', ht: '🇪🇨 Ekwatè' } },
    { value: 'America/Panama',                 label: { fr: '🇵🇦 Panama', en: '🇵🇦 Panama', es: '🇵🇦 Panamá', pt: '🇵🇦 Panamá', ht: '🇵🇦 Panama' } },
    { value: 'America/Guatemala',              label: { fr: '🇬🇹 Guatemala / Amérique centrale', en: '🇬🇹 Guatemala / Central America', es: '🇬🇹 Guatemala / América Central', pt: '🇬🇹 Guatemala / América Central', ht: '🇬🇹 Gwatemala / Amerik Santral' } },
    { value: 'America/Tegucigalpa',            label: { fr: '🇭🇳 Honduras', en: '🇭🇳 Honduras', es: '🇭🇳 Honduras', pt: '🇭🇳 Honduras', ht: '🇭🇳 Ondiras' } },
    { value: 'America/Managua',                label: { fr: '🇳🇮 Nicaragua', en: '🇳🇮 Nicaragua', es: '🇳🇮 Nicaragua', pt: '🇳🇮 Nicarágua', ht: '🇳🇮 Nikaragwa' } },
    { value: 'America/Costa_Rica',             label: { fr: '🇨🇷 Costa Rica', en: '🇨🇷 Costa Rica', es: '🇨🇷 Costa Rica', pt: '🇨🇷 Costa Rica', ht: '🇨🇷 Kostarika' } },
    { value: 'America/La_Paz',                 label: { fr: '🇧🇴 Bolivie', en: '🇧🇴 Bolivia', es: '🇧🇴 Bolivia', pt: '🇧🇴 Bolívia', ht: '🇧🇴 Bolivi' } },
    { value: 'America/Manaus',                 label: { fr: '🇧🇷 Brésil (Manaus / Amazonie)', en: '🇧🇷 Brazil (Manaus / Amazon)', es: '🇧🇷 Brasil (Manaos / Amazonía)', pt: '🇧🇷 Brasil (Manaus / Amazônia)', ht: '🇧🇷 Brezil (Manaus / Amazoni)' } },
  ],
  europe: [
    { value: 'Europe/London',      label: { fr: '🇬🇧 Londres', en: '🇬🇧 London', es: '🇬🇧 Londres', pt: '🇬🇧 Londres', ht: '🇬🇧 Lond' } },
    { value: 'Europe/Paris',       label: { fr: '🇫🇷 Paris / Bruxelles / Genève', en: '🇫🇷 Paris / Brussels / Geneva', es: '🇫🇷 París / Bruselas / Ginebra', pt: '🇫🇷 Paris / Bruxelas / Genebra', ht: '🇫🇷 Pari / Briksèl / Jenèv' } },
    { value: 'Europe/Berlin',      label: { fr: '🇩🇪 Berlin / Amsterdam / Rome', en: '🇩🇪 Berlin / Amsterdam / Rome', es: '🇩🇪 Berlín / Ámsterdam / Roma', pt: '🇩🇪 Berlim / Amsterdã / Roma', ht: '🇩🇪 Bèlen / Amstèdam / Wòm' } },
    { value: 'Europe/Madrid',      label: { fr: '🇪🇸 Madrid / Barcelone', en: '🇪🇸 Madrid / Barcelona', es: '🇪🇸 Madrid / Barcelona', pt: '🇪🇸 Madri / Barcelona', ht: '🇪🇸 Madrid / Baselòn' } },
    { value: 'Europe/Lisbon',      label: { fr: '🇵🇹 Lisbonne', en: '🇵🇹 Lisbon', es: '🇵🇹 Lisboa', pt: '🇵🇹 Lisboa', ht: '🇵🇹 Lisbòn' } },
    { value: 'Europe/Moscow',      label: { fr: '🇷🇺 Moscou', en: '🇷🇺 Moscow', es: '🇷🇺 Moscú', pt: '🇷🇺 Moscou', ht: '🇷🇺 Moskou' } },
    { value: 'Europe/Dublin',      label: { fr: '🇮🇪 Irlande', en: '🇮🇪 Ireland', es: '🇮🇪 Irlanda', pt: '🇮🇪 Irlanda', ht: '🇮🇪 Irlann' } },
    { value: 'Atlantic/Reykjavik', label: { fr: '🇮🇸 Islande', en: '🇮🇸 Iceland', es: '🇮🇸 Islandia', pt: '🇮🇸 Islândia', ht: '🇮🇸 Islann' } },
    { value: 'Europe/Stockholm',   label: { fr: '🇸🇪 Suède / Scandinavie', en: '🇸🇪 Sweden / Scandinavia', es: '🇸🇪 Suecia / Escandinavia', pt: '🇸🇪 Suécia / Escandinávia', ht: '🇸🇪 Swèd / Eskandinavi' } },
    { value: 'Europe/Warsaw',      label: { fr: '🇵🇱 Pologne', en: '🇵🇱 Poland', es: '🇵🇱 Polonia', pt: '🇵🇱 Polônia', ht: '🇵🇱 Polòy' } },
    { value: 'Europe/Athens',      label: { fr: '🇬🇷 Grèce', en: '🇬🇷 Greece', es: '🇬🇷 Grecia', pt: '🇬🇷 Grécia', ht: '🇬🇷 Grès' } },
    { value: 'Europe/Bucharest',   label: { fr: '🇷🇴 Roumanie / Bulgarie', en: '🇷🇴 Romania / Bulgaria', es: '🇷🇴 Rumanía / Bulgaria', pt: '🇷🇴 Romênia / Bulgária', ht: '🇷🇴 Woumani / Bilgari' } },
    { value: 'Europe/Helsinki',    label: { fr: '🇫🇮 Finlande', en: '🇫🇮 Finland', es: '🇫🇮 Finlandia', pt: '🇫🇮 Finlândia', ht: '🇫🇮 Finland' } },
    { value: 'Europe/Kyiv',        label: { fr: '🇺🇦 Ukraine', en: '🇺🇦 Ukraine', es: '🇺🇦 Ucrania', pt: '🇺🇦 Ucrânia', ht: '🇺🇦 Ikrèn' } },
    { value: 'Europe/Istanbul',    label: { fr: '🇹🇷 Turquie', en: '🇹🇷 Turkey', es: '🇹🇷 Turquía', pt: '🇹🇷 Turquia', ht: '🇹🇷 Tikri' } },
    { value: 'Europe/Vilnius',     label: { fr: '🇱🇹 Pays baltes (Lituanie / Lettonie / Estonie)', en: '🇱🇹 Baltic States (Lithuania / Latvia / Estonia)', es: '🇱🇹 Países bálticos (Lituania / Letonia / Estonia)', pt: '🇱🇹 Países bálticos (Lituânia / Letônia / Estônia)', ht: '🇱🇹 Peyi Balt yo (Litiyani / Letoni / Estoni)' } },
  ],
  afrique: [
    { value: 'Africa/Abidjan',      label: { fr: "🇨🇮 Côte d'Ivoire / Sénégal / Mali", en: "🇨🇮 Côte d'Ivoire / Senegal / Mali", es: "🇨🇮 Costa de Marfil / Senegal / Malí", pt: "🇨🇮 Costa do Marfim / Senegal / Mali", ht: '🇨🇮 Kotdivwa / Senegal / Mali' } },
    { value: 'Africa/Lagos',        label: { fr: '🇳🇬 Nigeria / Cameroun / Gabon', en: '🇳🇬 Nigeria / Cameroon / Gabon', es: '🇳🇬 Nigeria / Camerún / Gabón', pt: '🇳🇬 Nigéria / Camarões / Gabão', ht: '🇳🇬 Nijerya / Kamewoun / Gabon' } },
    { value: 'Africa/Kinshasa',     label: { fr: '🇨🇩 Congo / RDC', en: '🇨🇩 Congo / DRC', es: '🇨🇩 Congo / RDC', pt: '🇨🇩 Congo / RDC', ht: '🇨🇩 Kongo / RDK' } },
    { value: 'Africa/Nairobi',      label: { fr: '🇰🇪 Kenya / Éthiopie / Tanzanie', en: '🇰🇪 Kenya / Ethiopia / Tanzania', es: '🇰🇪 Kenia / Etiopía / Tanzania', pt: '🇰🇪 Quênia / Etiópia / Tanzânia', ht: '🇰🇪 Kenya / Etyopi / Tanzani' } },
    { value: 'Africa/Casablanca',   label: { fr: '🇲🇦 Maroc', en: '🇲🇦 Morocco', es: '🇲🇦 Marruecos', pt: '🇲🇦 Marrocos', ht: '🇲🇦 Marok' } },
    { value: 'Africa/Cairo',        label: { fr: '🇪🇬 Égypte', en: '🇪🇬 Egypt', es: '🇪🇬 Egipto', pt: '🇪🇬 Egito', ht: '🇪🇬 Ejip' } },
    { value: 'Indian/Reunion',      label: { fr: '🇷🇪 La Réunion / Maurice', en: '🇷🇪 Réunion / Mauritius', es: '🇷🇪 Reunión / Mauricio', pt: '🇷🇪 Reunião / Maurícia', ht: '🇷🇪 La Reyinyon / Moris' } },
    { value: 'Africa/Johannesburg', label: { fr: '🇿🇦 Afrique du Sud / Zimbabwe / Botswana', en: '🇿🇦 South Africa / Zimbabwe / Botswana', es: '🇿🇦 Sudáfrica / Zimbabue / Botsuana', pt: '🇿🇦 África do Sul / Zimbábue / Botsuana', ht: '🇿🇦 Afrik di Sid / Zimbabwe / Botswana' } },
    { value: 'Africa/Maputo',       label: { fr: '🇲🇿 Mozambique / Zambie / Malawi', en: '🇲🇿 Mozambique / Zambia / Malawi', es: '🇲🇿 Mozambique / Zambia / Malaui', pt: '🇲🇿 Moçambique / Zâmbia / Malawi', ht: '🇲🇿 Mozanbik / Zanbi / Malawi' } },
    { value: 'Africa/Windhoek',     label: { fr: '🇳🇦 Namibie', en: '🇳🇦 Namibia', es: '🇳🇦 Namibia', pt: '🇳🇦 Namíbia', ht: '🇳🇦 Namibi' } },
    { value: 'Africa/Tunis',        label: { fr: '🇹🇳 Tunisie / Algérie / Libye', en: '🇹🇳 Tunisia / Algeria / Libya', es: '🇹🇳 Túnez / Argelia / Libia', pt: '🇹🇳 Tunísia / Argélia / Líbia', ht: '🇹🇳 Tinizi / Aljeri / Libi' } },
    { value: 'Africa/Accra',        label: { fr: '🇬🇭 Ghana', en: '🇬🇭 Ghana', es: '🇬🇭 Ghana', pt: '🇬🇭 Gana', ht: '🇬🇭 Gana' } },
    { value: 'Africa/Khartoum',     label: { fr: '🇸🇩 Soudan', en: '🇸🇩 Sudan', es: '🇸🇩 Sudán', pt: '🇸🇩 Sudão', ht: '🇸🇩 Soudan' } },
    { value: 'Africa/Luanda',       label: { fr: '🇦🇴 Angola', en: '🇦🇴 Angola', es: '🇦🇴 Angola', pt: '🇦🇴 Angola', ht: '🇦🇴 Angola' } },
    { value: 'Africa/Kigali',       label: { fr: '🇷🇼 Rwanda / Burundi', en: '🇷🇼 Rwanda / Burundi', es: '🇷🇼 Ruanda / Burundi', pt: '🇷🇼 Ruanda / Burundi', ht: '🇷🇼 Rwanda / Burundi' } },
    { value: 'Africa/Mogadishu',    label: { fr: '🇸🇴 Somalie / Djibouti / Érythrée', en: '🇸🇴 Somalia / Djibouti / Eritrea', es: '🇸🇴 Somalia / Yibuti / Eritrea', pt: '🇸🇴 Somália / Djibuti / Eritreia', ht: '🇸🇴 Somali / Jibouti / Eritre' } },
    { value: 'UTC',                 label: { fr: '🌍 UTC — événement international / en ligne', en: '🌍 UTC — international / online event', es: '🌍 UTC — evento internacional / en línea', pt: '🌍 UTC — evento internacional / online', ht: '🌍 UTC — evènman entènasyonal / sou entènèt' } },
  ],
  asie: [
    { value: 'Asia/Beirut',      label: { fr: '🇱🇧 Liban', en: '🇱🇧 Lebanon', es: '🇱🇧 Líbano', pt: '🇱🇧 Líbano', ht: '🇱🇧 Liban' } },
    { value: 'Asia/Riyadh',      label: { fr: '🇸🇦 Arabie Saoudite / Koweït', en: '🇸🇦 Saudi Arabia / Kuwait', es: '🇸🇦 Arabia Saudita / Kuwait', pt: '🇸🇦 Arábia Saudita / Kuwait', ht: '🇸🇦 Arabi Saoudit / Koweit' } },
    { value: 'Asia/Dubai',       label: { fr: '🇦🇪 Dubaï / EAU', en: '🇦🇪 Dubai / UAE', es: '🇦🇪 Dubái / EAU', pt: '🇦🇪 Dubai / EAU', ht: '🇦🇪 Doubay / EAU' } },
    { value: 'Asia/Tehran',      label: { fr: '🇮🇷 Iran', en: '🇮🇷 Iran', es: '🇮🇷 Irán', pt: '🇮🇷 Irã', ht: '🇮🇷 Iran' } },
    { value: 'Asia/Karachi',     label: { fr: '🇵🇰 Pakistan', en: '🇵🇰 Pakistan', es: '🇵🇰 Pakistán', pt: '🇵🇰 Paquistão', ht: '🇵🇰 Pakistan' } },
    { value: 'Asia/Kolkata',     label: { fr: '🇮🇳 Inde', en: '🇮🇳 India', es: '🇮🇳 India', pt: '🇮🇳 Índia', ht: '🇮🇳 End' } },
    { value: 'Asia/Dhaka',       label: { fr: '🇧🇩 Bangladesh', en: '🇧🇩 Bangladesh', es: '🇧🇩 Bangladés', pt: '🇧🇩 Bangladesh', ht: '🇧🇩 Bangladèch' } },
    { value: 'Asia/Bangkok',     label: { fr: '🇹🇭 Thaïlande / Vietnam / Cambodge', en: '🇹🇭 Thailand / Vietnam / Cambodia', es: '🇹🇭 Tailandia / Vietnam / Camboya', pt: '🇹🇭 Tailândia / Vietnã / Camboja', ht: '🇹🇭 Tayilann / Vyetnam / Kanbòdj' } },
    { value: 'Asia/Singapore',   label: { fr: '🇸🇬 Singapour / Malaisie / Philippines', en: '🇸🇬 Singapore / Malaysia / Philippines', es: '🇸🇬 Singapur / Malasia / Filipinas', pt: '🇸🇬 Singapura / Malásia / Filipinas', ht: '🇸🇬 Singapou / Malezi / Filipin' } },
    { value: 'Asia/Jakarta',     label: { fr: '🇮🇩 Indonésie', en: '🇮🇩 Indonesia', es: '🇮🇩 Indonesia', pt: '🇮🇩 Indonésia', ht: '🇮🇩 Endonezi' } },
    { value: 'Asia/Shanghai',    label: { fr: '🇨🇳 Chine / Hong Kong / Taïwan', en: '🇨🇳 China / Hong Kong / Taiwan', es: '🇨🇳 China / Hong Kong / Taiwán', pt: '🇨🇳 China / Hong Kong / Taiwan', ht: '🇨🇳 Lachin / Hong Kong / Tayiwann' } },
    { value: 'Asia/Seoul',       label: { fr: '🇰🇷 Corée du Sud', en: '🇰🇷 South Korea', es: '🇰🇷 Corea del Sur', pt: '🇰🇷 Coreia do Sul', ht: '🇰🇷 Kore di Sid' } },
    { value: 'Asia/Tokyo',       label: { fr: '🇯🇵 Japon', en: '🇯🇵 Japan', es: '🇯🇵 Japón', pt: '🇯🇵 Japão', ht: '🇯🇵 Japon' } },
    { value: 'Asia/Jerusalem',   label: { fr: '🇮🇱 Israël / Palestine', en: '🇮🇱 Israel / Palestine', es: '🇮🇱 Israel / Palestina', pt: '🇮🇱 Israel / Palestina', ht: '🇮🇱 Izrayèl / Palestin' } },
    { value: 'Asia/Amman',       label: { fr: '🇯🇴 Jordanie / Syrie', en: '🇯🇴 Jordan / Syria', es: '🇯🇴 Jordania / Siria', pt: '🇯🇴 Jordânia / Síria', ht: '🇯🇴 Jòdani / Siri' } },
    { value: 'Asia/Nicosia',     label: { fr: '🇨🇾 Chypre', en: '🇨🇾 Cyprus', es: '🇨🇾 Chipre', pt: '🇨🇾 Chipre', ht: '🇨🇾 Chip' } },
    { value: 'Asia/Baghdad',     label: { fr: '🇮🇶 Irak', en: '🇮🇶 Iraq', es: '🇮🇶 Irak', pt: '🇮🇶 Iraque', ht: '🇮🇶 Irak' } },
    { value: 'Asia/Qatar',       label: { fr: '🇶🇦 Qatar / Bahreïn', en: '🇶🇦 Qatar / Bahrain', es: '🇶🇦 Catar / Baréin', pt: '🇶🇦 Catar / Bahrein', ht: '🇶🇦 Kata / Bahren' } },
    { value: 'Asia/Kabul',       label: { fr: '🇦🇫 Afghanistan', en: '🇦🇫 Afghanistan', es: '🇦🇫 Afganistán', pt: '🇦🇫 Afeganistão', ht: '🇦🇫 Afganistan' } },
    { value: 'Asia/Kathmandu',   label: { fr: '🇳🇵 Népal', en: '🇳🇵 Nepal', es: '🇳🇵 Nepal', pt: '🇳🇵 Nepal', ht: '🇳🇵 Nepal' } },
    { value: 'Asia/Yangon',      label: { fr: '🇲🇲 Birmanie (Myanmar)', en: '🇲🇲 Myanmar (Burma)', es: '🇲🇲 Birmania (Myanmar)', pt: '🇲🇲 Mianmar (Birmânia)', ht: '🇲🇲 Myanma (Birmani)' } },
    { value: 'Asia/Tashkent',    label: { fr: '🇺🇿 Ouzbékistan / Tadjikistan / Turkménistan', en: '🇺🇿 Uzbekistan / Tajikistan / Turkmenistan', es: '🇺🇿 Uzbekistán / Tayikistán / Turkmenistán', pt: '🇺🇿 Uzbequistão / Tajiquistão / Turcomenistão', ht: '🇺🇿 Ouzbekistan / Tadjikistan / Tirkmenistan' } },
    { value: 'Asia/Almaty',      label: { fr: '🇰🇿 Kazakhstan (Est) / Kirghizistan', en: '🇰🇿 Kazakhstan (East) / Kyrgyzstan', es: '🇰🇿 Kazajistán (Este) / Kirguistán', pt: '🇰🇿 Cazaquistão (Leste) / Quirguistão', ht: '🇰🇿 Kazakstan (Lès) / Kirgizistan' } },
    { value: 'Asia/Ulaanbaatar', label: { fr: '🇲🇳 Mongolie', en: '🇲🇳 Mongolia', es: '🇲🇳 Mongolia', pt: '🇲🇳 Mongólia', ht: '🇲🇳 Mongoli' } },
    { value: 'Asia/Baku',        label: { fr: '🇦🇿 Azerbaïdjan / Caucase', en: '🇦🇿 Azerbaijan / Caucasus', es: '🇦🇿 Azerbaiyán / Cáucaso', pt: '🇦🇿 Azerbaijão / Cáucaso', ht: '🇦🇿 Azèbidjan / Kokaz' } },
  ],
  oceanie: [
    { value: 'Australia/Sydney',     label: { fr: '🇦🇺 Australie (Sydney)', en: '🇦🇺 Australia (Sydney)', es: '🇦🇺 Australia (Sídney)', pt: '🇦🇺 Austrália (Sydney)', ht: '🇦🇺 Ostrali (Sidney)' } },
    { value: 'Pacific/Auckland',     label: { fr: '🇳🇿 Nouvelle-Zélande', en: '🇳🇿 New Zealand', es: '🇳🇿 Nueva Zelanda', pt: '🇳🇿 Nova Zelândia', ht: '🇳🇿 Nouvèl Zeland' } },
    { value: 'Pacific/Honolulu',     label: { fr: '🇺🇸 Hawaï', en: '🇺🇸 Hawaii', es: '🇺🇸 Hawái', pt: '🇺🇸 Havaí', ht: '🇺🇸 Hawayi' } },
    { value: 'Australia/Perth',      label: { fr: '🇦🇺 Australie (Perth)', en: '🇦🇺 Australia (Perth)', es: '🇦🇺 Australia (Perth)', pt: '🇦🇺 Austrália (Perth)', ht: '🇦🇺 Ostrali (Pèt)' } },
    { value: 'Australia/Adelaide',   label: { fr: '🇦🇺 Australie (Adelaide / Darwin)', en: '🇦🇺 Australia (Adelaide / Darwin)', es: '🇦🇺 Australia (Adelaida / Darwin)', pt: '🇦🇺 Austrália (Adelaide / Darwin)', ht: '🇦🇺 Ostrali (Adelayid / Darwin)' } },
    { value: 'Pacific/Fiji',         label: { fr: '🇫🇯 Fidji', en: '🇫🇯 Fiji', es: '🇫🇯 Fiyi', pt: '🇫🇯 Fiji', ht: '🇫🇯 Fidji' } },
    { value: 'Pacific/Port_Moresby', label: { fr: '🇵🇬 Papouasie-Nouvelle-Guinée / Îles Salomon', en: '🇵🇬 Papua New Guinea / Solomon Islands', es: '🇵🇬 Papúa Nueva Guinea / Islas Salomón', pt: '🇵🇬 Papua-Nova Guiné / Ilhas Salomão', ht: '🇵🇬 Papwazi-Nouvèl Gine / Zile Salomon' } },
  ],
}
